fix: client registration and refactor it
coronareportteam/coronareportfrontend pull request #41
Opened 2020-04-01 15:04 UTC by danielreichler

2020-04-01 16:18 UTC, VILLAN3LL3 requested changes

2020-04-01 16:18 UTC, JulidaRocks commented on src/app/services/user.service.ts
> +    // return this.apiService.registerClient(this.createBackendClient(client, firstQuery));
der auskommentierte Code kann raus, oder?

2020-04-02 06:46 UTC, danielreichler commented on src/app/services/user.service.ts
> +    // return this.apiService.registerClient(this.createBackendClient(client, firstQuery));
Stimmt, ist geändert.

2020-04-02 06:58 UTC, VILLAN3LL3 requested changes

2020-04-02 06:58 UTC, JulidaRocks commented on src/app/services/user.service.ts
> +    // return this.apiService.registerClient(this.createBackendClient(client, firstQuery));
Wird mir immer noch angezeigt?

2020-04-02 10:27 UTC, danielreichler commented on src/app/services/user.service.ts
> +    // return this.apiService.registerClient(this.createBackendClient(client, firstQuery));
Jetzte aber :)

2020-04-02 11:08 UTC, VILLAN3LL3 approved these changes

2020-04-02 11:09 UTC, merged